# Generated by Django 4.2.16 on 2024-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitme',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
